### ISSUE TITLE
Разное - <img> width, height атрибуты

### ISSUE THREAD

**Issue by thrnd** [epixx/code-guide#4]
Последний пункт в "Разном":
"Для тегов <img> должны быть указаны размеры (в пикселях или процентах)."

Я недавно читал в какой-то англоязычной статье, что в этих атрибутах для тега img нужно задавать числа без единиц измерения (то бишь, только в пикселях). Ибо эти размеры нужны для браузера, чтобы понять какой размер у картинки до того, как она загрузится.
Поправь меня, если не так понял. Я всего лишь только вылупившийся веб-птенец из инкубатора html-academy =)

**Comment by nicothin** [comment]
Ну так когда нужно показывать картинку, браузер уже что-то знает про размер блока, от которого проценты. Хотя, полагаю, некоторое ужесточение (до пикселей) пойдет только на пользу.
